### ISSUE TITLE
Docker API Version (Solved issue)

### ISSUE THREAD

**Issue by dz3n** [aacebedo/dnsdock#107]
if you have similar issue like this:

**Error getting containers: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version**

This fork and docker repo may help you. The docker API version is updated to the latest one

https://github.com/dz3n/dnsdock
https://hub.docker.com/r/dz3n/dnsdock

`docker run --restart=always -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock   -p 172.17.0.1:53:53/udp dz3n/dnsdock:1.0`

**Comment by ailequal** [comment]
I am running `Ubuntu 22.04.3 LTS x86_64` with `Docker version 25.0.0, build e758fe5` and `Docker Compose version v2.24.1` and I have the same issue.

**Comment by thaJeztah** [comment]
It looks like this repository hasn't been maintained for many Years; API version v1.22 is deprecated, disabled by default in Docker v25.0, and will be removed in Docker v26.0; see https://docs.docker.com/engine/deprecated/#deprecate-legacy-api-versions

> ### Deprecate legacy API versions
> 
> **Deprecated in Release: v25.0**
> **Target For Removal In Release: v26.0**
> 
> The Docker daemon provides a versioned API for backward compatibility with old
> clients. Docker clients can perform API-version negotiation to select the most
> recent API version supported by the daemon (downgrading to and older version of
> the API when necessary). API version negotiation was introduced in Docker v1.12.0
> (API 1.24), and clients before that used a fixed API version.
> 
> Docker Engine versions through v25.0 provide support for all [API versions](https://docs.docker.com/engine/api/#api-version-matrix)
> included in stable releases for a given platform. For Docker daemons on Linux,
> the earliest supported API version is 1.12 (corresponding with Docker Engine
> v1.0.0), whereas for Docker daemons on Windows, the earliest supported API
> version is 1.24 (corresponding with Docker Engine v1.12.0).
> 
> Support for legacy API versions (providing old API versions on current versions
> of the Docker Engine) is primarily intended to provide compatibility with recent,
> but still supported versions of the client, which is a common scenario (the Docker
> daemon may be updated to the latest release, but not all clients may be up-to-date
> or vice versa). Support for API versions before that (API versions provided by
> EOL versions of the Docker Daemon) is provided on a "best effort" basis.
> 
> Use of old API versions is very rare, and support for legacy API versions
> involves significant complexity (Docker 1.0.0 having been released 10 years ago).
> Because of this, we'll start deprecating support for legacy API versions.
> 
> Docker Engine v25.0 by default disables API version older than 1.24 (aligning
> the minimum supported API version between Linux and Windows daemons). When
> connecting with a client that uses an API version version older than 1.24,
> the daemon returns an error. The following example configures the docker
> CLI to use API version 1.23, which produces an error:
> 
> ```console
> DOCKER_API_VERSION=1.23 docker version
> Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
> ```
> 
> An environment variable (`DOCKER_MIN_API_VERSION`) is introduced that allows
> re-enabling older API versions in the daemon. This environment variable must
> be set in the daemon's environment (for example, through a [systemd override
> file](https://docs.docker.com/config/daemon/systemd/)), and the specified
> API version must be supported by the daemon (`1.12` or higher on Linux, or
> `1.24` or higher on Windows).
> 
> Support for API versions lower than `1.24` will be permanently removed in Docker
> Engine v26, and the minimum supported API version will be incrementally raised
> in releases following that.
> 
> We do not recommend depending on the `DOCKER_MIN_API_VERSION` environment
> variable other than for exceptional cases where it's not possible to update
> old clients, and those clients must be supported.

**Comment by aacebedo** [comment]
I did not update the repo since a long time but if do a PR I can merge it.

**Comment by dz3n** [comment]
> I did not update the repo since a long time but if do a PR I can merge it.

The PR is created. 

Additionally, it would be great if you could create a new build for Docker Hub based on these changes. This update would be useful for everyone using this library.

**Comment by aacebedo** [comment]
I have merged the PR and started a new branch to revamp all tooling and maybe some code if I have time (I worked on a porting to cobra but never finished it for instance).

Next I will add github actions as travis is dead now.

**Comment by aacebedo** [comment]
I have added the necessary stuff to modernize the CI/CD pipeline.

From now modern tooling is available:
- you can use devbox or devcontainers to get a ready to go dev environment
- images are pushed automatically to docker hub

If forks would like to get reintegrated do not hesitate to do PRs
