### ISSUE TITLE
dnsdock v1.17.0: Several vulnerabilities found

### ISSUE THREAD

**Issue by crt0r** [aacebedo/dnsdock#112]
Hello!
First of all, thank you for developing this project!

Our company's internal installation of Trivy has found several vulnerabilities present in the [dnsdock container image](https://hub.docker.com/r/aacebedo/dnsdock/tags) version `1.17.0` for `amd64`.

I am not sure if this info is of any use for you, but thought it might be good to share.
![b0b0c211-988f-43ff-939b-02ee14b54f3b](https://github.com/aacebedo/dnsdock/assets/56602996/e9b7700b-7e06-4231-9943-bff8da900ba6)

I have attached a CSV-formatted export containing the list of vulnerabilities below:
[csv_file_20240301120432.csv](https://github.com/aacebedo/dnsdock/files/14458925/csv_file_20240301120432.csv)

edit: typo

**Comment by aacebedo** [comment]
Thanks. It means I need to update deps one by one

**Comment by aacebedo** [comment]
I have updated the dep. Can you try this version and tell me if it fixes the CVEs ? https://github.com/aacebedo/dnsdock/releases/tag/v1.18.0-rc1
Thanks !

**Comment by crt0r** [comment]
Yup, Trivy doesn't scream at me now. I've tried both [the tar archive](https://github.com/aacebedo/dnsdock/releases/download/v1.18.0-rc1/dnsdock_.1.18.0-rc1_.linux_.amd64.tar.gz) and [the OCI Image](https://hub.docker.com/layers/aacebedo/dnsdock/v1.18.0-rc1-amd64/images/sha256-e26a5772efc2a01bc11ec185f5c99c48f9978ef817c2e92ba28c3d5dd72bc83e?context=explore).
