### ISSUE TITLE
no official docker builds?

### ISSUE THREAD

**Issue by tcurdt** [aacebedo/dnsdock#115]
I was just trying to give this a try but could not find an image:

```
docker pull aacebedo/dnsdock
Using default tag: latest
Error response from daemon: manifest for aacebedo/dnsdock:latest not found: manifest unknown: manifest unknown
```

but then by random found:

`docker pull aacebedo/dnsdock:latest-amd64`

Would be great to add the details to the README or provide a multiarch image.

Thanks for the project. If it works as advertised it will be incredibly useful.

**Comment by aacebedo** [comment]
Thanks for the issue. You're right I will ad details on README

**Comment by aacebedo** [comment]
done in v1.18.0-rc2
