### ISSUE TITLE
Containers not discoverable from host

### ISSUE THREAD

**Issue by Vad1mo** [aacebedo/dnsdock#14]
I try to access my containers from my mac os HOST.
I followed the description of the page and modified the nic2 in the vm. So now I can ping the containers by IP

```
sudo route -n add -net 172.17.0.0 192.168.59.103

ping 172.17.0.3
PING 172.17.0.3 (172.17.0.3): 56 data bytes
```

My next step was to also access the container via its dnsdock domain name. So I added a file in `/etc/resolver/project.docker` with

```
nameserver 172.17.42.1
```

I am still not able to ping the container via its dns name. Any idea what this can be or how I can verify my setup is correct?

**Comment by tonistiigi** [comment]
First, test if the server is responding properly from host by running `dig @172.17.42.1 docker`.

Using filename `project.docker` means that you want to use this nameserver for domains that look like `*.project.docker`. If you use the default settings and only one `dnsdock` instance the filename should be just `docker`.

I've had trouble with the resolver updating when I make changes to the files under `/etc/resolver/`. When you need to modify these files it is safer to remove the old file and add new.

**Comment by zyguan** [comment]
Hi, I also have trouble with it. The output in my computer is shown below:
```
$ docker ps
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS                    NAMES
cfd81fd64d38        zyguan/hadoop        "/bin/bash"         20 minutes ago      Up 20 minutes                                test                
8e77b15c7e51        tonistiigi/dnsdock   "/go/bin/dnsdock"   3 days ago          Up 31 minutes       172.17.42.1:53->53/udp   dnsdock             

$ dig dnsdock.dnsdock.docker

; <<>> DiG 9.9.5-3-Ubuntu <<>> dnsdock.dnsdock.docker
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59651
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;dnsdock.dnsdock.docker.		IN	A

;; ANSWER SECTION:
dnsdock.dnsdock.docker.	0	IN	A	172.17.0.1

;; Query time: 0 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Wed Jul 29 10:34:21 CST 2015
;; MSG SIZE  rcvd: 78

$ ping -c 3 dnsdock.dnsdock.docker
PING dnsdock.dnsdock.docker (172.17.0.1) 56(84) bytes of data.
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=1 ttl=64 time=0.053 ms
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=2 ttl=64 time=0.066 ms
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=3 ttl=64 time=0.062 ms

--- dnsdock.dnsdock.docker ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.053/0.060/0.066/0.008 ms

$ host dnsdock.dnsdock.docker
Host dnsdock.dnsdock.docker not found: 3(NXDOMAIN)

$ nslookup dnsdock.dnsdock.docker
;; Got recursion not available from 172.17.42.1, trying next server
Server:		192.168.0.1
Address:	192.168.0.1#53

** server can't find dnsdock.dnsdock.docker: NXDOMAIN

$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.17.42.1
nameserver 192.168.0.1
```

```dig``` works fine for me, but ```nslookup``` and ```host``` do not. I started dnsdock by ```docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.42.1:53:53/udp tonistiigi/dnsdock```, did I miss something?

BTW, the java code below doesn't work either.
``` java
import java.net.InetAddress;
import java.io.IOException;

public class DNSTest {
    public static void main(String[] args) throws IOException {
        InetAddress addr = InetAddress.getByName(args[0]);
        System.out.println(addr);
    }
}
```

**Comment by spacejam** [comment]
Also hitting this.  Found this post about suspiciously similar symptoms: https://geekmush.wordpress.com/2014/01/28/ssh-could-not-resolve-hostname-base-geekmush-org-no-address-associated-with-hostname-but-ping-works/  Could the same thing with SkyDNS AAAA records that this guy found be happening here?

**Comment by spacejam** [comment]
I fixed my issue by switching my container's base image from ubuntu to debian.  I've not looked into what the actual changed resolution logic was that fixed it.

**Comment by spacejam** [comment]
By switching my containers from ubuntu to debian it has fixed my issue.  I've not looked into the actual difference in resolution that this yields, or if there's a better solution for making this just work with ubuntu base images, or if this is ubuntu specific, so this 'fix' should be considered a fast hack.

**Comment by zyguan** [comment]
@spacejam, thanks for reply. I did some tests and got following results:

**dnsdock**

![dnsdock](https://cloud.githubusercontent.com/assets/6850317/9021302/513ac742-386e-11e5-8d98-fe1bf4a18b69.png)

**skydns**

![skydns](https://cloud.githubusercontent.com/assets/6850317/9021303/588ff67a-386e-11e5-805b-ba59373a3a55.png)

skydns works fine for me, however I got ```;; Got recursion not available from 172.17.42.1, trying next server``` when using dnsdock. I don't know much about DNS, maybe it's the response flags that cause this issue.

**Comment by zyguan** [comment]
Well, after adding `-norecur` option, `nslookup` finally gave me a proper answer.

```
$ nslookup -norecur dnsdock.dnsdock.docker
Server:		172.17.42.1
Address:	172.17.42.1#53

Non-authoritative answer:
Name:	dnsdock.dnsdock.docker
Address: 172.17.42.3

```

**Comment by tasuk** [comment]
Had something similar, using ipv4 (ie disabling ipv6) worked.
```
$ curl http://dnsdock.docker/services # doesn't work
$ curl -4 http://dnsdock.docker/services # works
```

**Comment by brdloush** [comment]
I'm also experiencing similar behavior. inside my running container the curl/wget doesn't resolve the host (while ping does)  and curl -4 actually works.
