### ISSUE TITLE
Manage Multiples Nameservers

### ISSUE THREAD

**Issue by khena** [aacebedo/dnsdock#29]
Hi,

First, thank you for this container ! Nice & easy :)

In production, we use multiples dns servers. I see the dnsdock actually manage only one dns external server (google by default).

I tried to read the go script, and i found this code :
In the function handleOrForward, when you call the  Exchange function of the dns client library,
you read directly the config structure, with the nameserver.

I sugget to :

- split the nameserver string with comma separator into a array (or something equivalent in go)
- count the nameservers
- while err != nil and all the servers have not yet been tested
  - randomize and take a another nameserver
  - try it :)
  - go out the 'while' or take another nameserver
- clear the array!

Maybe the array must be created on constructor and release at the end (use a error server list in this case)

I prefer use the random function to balance the charge, but one by one is nice too :)

-> only one server, nothing change!
-> with multiples servers, we use the same syntax than skydns/skydock

thank you for your attention :)

ps : sorry i'm not a golang dev, i can't do it myself !

**Comment by tonistiigi** [comment]
Yes, makes sense to add this.

**Comment by febbraro** [comment]
This was already implemented in another commit, but was not fully baked. I added a PR to fix it here: #73
