### ISSUE TITLE
wrong service stop detection when using signals

### ISSUE THREAD

**Issue by greg0ire** [aacebedo/dnsdock#40]
I have an nginx container. My nginx configuration is mounted on it, and when I tweak it, I would like to be able to reload the configuration without restarting the container. [The nginx docs](http://wiki.nginx.org/CommandLine) show that sending a HUP signal to the master process should do the trick. With docker compose, you can do this by issuing the following command : 

> docker-compose kill -s HUP webserver

When I do that, dnsdock logs this : 

> 2015/08/24 12:25:50 Stopped service: 747bc57f0d326be9464bfe2253496848dd99e3963e680bc7741ddaac9b8a792c

I would expect it to not detect this false positive.

The [switch statement that takes care of this is too naïve](https://github.com/tonistiigi/dnsdock/blob/66748d0c622c6ee6a818c7b9dce21eab60495ce7/docker.go#L89), it should inspect the kill arguments.

**Comment by jsteinberg** [comment]
I am also having this issue.  @greg0ire did you do anything to resolve this issue?

**Comment by jsteinberg** [comment]
For anyone experiencing similar issues(and using docker_gen for the conf generation), I fixed it by basically coping the docker file [FROM HERE](https://github.com/jwilder/nginx-proxy) and created a custom template file.  This allowed me to restart nginx with sending it a kill.

I do think there is still an issue with that switch statement, but I do not know enough yet about docker to provide a solution.

**Comment by greg0ire** [comment]
@jsteinberg : no, I rarely tweak my config so it is not that big a problem for me.
