### ISSUE TITLE
Alias not working inside ubuntu containers

### ISSUE THREAD

**Issue by diogogmt** [aacebedo/dnsdock#44]
I'm able to use the alias in my docker host but not inside the containers.

Here is the log from dns dock when I run a container with an alias:
`2015/09/03 13:19:34 Added service: f685a5b79f7b7331d7f61d1619ea72bf645f6b6a4be2317b1513bb5bbd938a56 {cdos_session_run_1 memcached 172.17.0.6 -1 ["session.cloud"]}`

When I try to resolve the alias inside an ubuntu container:
With the full name:

```
root@769f59ceb4d4:/usr/local/cdos/exosphere# dig cdos_session_run_1.memcached.cloud

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> cdos_session_run_1.memcached.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35519
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;cdos_session_run_1.memcached.cloud. IN A

;; ANSWER SECTION:
cdos_session_run_1.memcached.cloud. 0 IN A  172.17.0.6

;; Query time: 1 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Thu Sep 03 13:20:48 UTC 2015
;; MSG SIZE  rcvd: 102
```

With the alias:

```
root@769f59ceb4d4:/usr/local/cdos/exosphere# dig session.cloud

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> session.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 34616
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;session.cloud.         IN  A

;; AUTHORITY SECTION:
cloud.          0   IN  SOA dnsdock.cloud. dnsdock.dnsdock.cloud. 1441285200 28800 7200 604800 0

;; Query time: 10 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Thu Sep 03 13:20:53 UTC 2015
;; MSG SIZE  rcvd: 106

```

**Comment by kgutwin** [comment]
The quotation marks in the log (`"session.cloud"`) suggest that the quotation marks are being passed literally in the environment variable. 

    $ sudo docker inspect furious_fermi | grep test
            "DNSDOCK_ALIAS=\"testing.docker\""

That won't work - just leave the quotes out when starting the container and it should be fine.

    $ sudo docker run -d -e DNSDOCK_ALIAS=testing.docker busybox sleep 300
    731c88859245f0daec6522ee5d5f4c0e5c927ef2f7f39effe0b98670a1a1d310
