### ISSUE TITLE
container can't access DNS server while host can

### ISSUE THREAD

**Issue by thewilli** [aacebedo/dnsdock#50]
I followed your instructions and let the dnsdocker container listen on the docker0 interface and ip 172.17.42.1. I can access and query it successfully from the host, but no container is able to connect to it using this ip (they all have IPs from the range 172.17.42.1/24). If I use the actual (changing) IP from the dnsdock container, the clients can connect successfully. 

Any idea what the problem might be?

**Comment by arnaudmm** [comment]
I have the same issue here

**Comment by hekar** [comment]
Could this be a problem with Docker? What Docker version are you guys running?
