### ISSUE TITLE
Github releases don't match docker hub tags

### ISSUE THREAD

**Issue by michael-yx-wu** [aacebedo/dnsdock#58]
It looks like you recently updated the `latest` tag in the Docker hub, but I noticed that releases on Github number up to `v1.12.0` whereas you only have up to `v1.10.0` in the Docker hub. I'm assuming that `latest` in the Docker hub matches `v1.12.0` in Github, but I don't have anyway of finding out.

**Comment by hekar** [comment]
`latest` is probably not `v1.10.0`, because the image sizes are different. https://hub.docker.com/r/tonistiigi/dnsdock/tags/

latest 287 MB 7 days ago
v1.10.0 265 MB Unavailable

Also some people are complaining about defects that are only occurring on `latest` and not on `v1.10.0`.

**Comment by paolomainardi** [comment]
Just a follow up to this issue to understand which is the version scheme pattern we are using now, now we have:

Newer releases:
amd64-1.13.1
arm-1.13.1
amd64-dev

Older releases:
v1.10.0

Are we going to stick with the newer one ?

Thanks!

**Comment by aacebedo** [comment]
Hi.
I have pushed the two new images. However I do  not have the access to edit tags on the repository so I can't remove them.
I think that naming the image with vX.X.X-Arch is maybe better than the actual situation as it is more similar to the previous numbering.
What do you think about that?

**Comment by egeskow** [comment]
By default docker uses tag `latest` which is outdated. It could be really confusing. We can mention this in readme.

It is not obviously to
` docker pull tonistiigi/dnsdock:amd64-1.13.1`
rather than
` docker pull tonistiigi/dnsdock`.

Also new dnsdock repo can be created at docker hub

**Comment by aacebedo** [comment]
Docker does not support officially multi arch yet. 
If we want to use the latest tag we can create a new repo for arm arch and keep versions tagging on both.

**Comment by egeskow** [comment]
No need in second repo. Just choose default arch

**Comment by paolomainardi** [comment]
👍  to keep just one repo with -arch suffix.

**Comment by aacebedo** [comment]
Ok I'll keep one repo with the arch suffix.
I'll also add a <arch>-latest tag to keep the latest mechanism.
I prefer not to choose a default arch as it depends on each user

**Comment by paolomainardi** [comment]
thanks a lot for your great work @aacebedo, very much appreciated!

**Comment by aacebedo** [comment]
@paolomainardi you're welcome :)
