### ISSUE TITLE
DNS Forwarding only tries the first of multiple name servers

### ISSUE THREAD

**Issue by febbraro** [aacebedo/dnsdock#74]
If you configure multiple name servers via `-nameserver=10.10.10.2:53,8.8.8.8:53` and try to resolve a name that does not end in `.docker` (or whatever you have configured `-domain` to be) you will see that it only tries the first server, prints a log message that it is trying the next server, but then just sends the failure response and returns.  

PR #73 will try all name servers and will only fail when each of those name servers have failed to resolve.

**Comment by aacebedo** [comment]
Fixed in #73
