### ISSUE TITLE
The command option format has been changed from `-<option>` to `--<option>` in v1.16.0.

### ISSUE THREAD

**Issue by ailispaw** [aacebedo/dnsdock#79]
It's not good and should be documented.

**Comment by aacebedo** [comment]
I didn't notice this change before the release. 
I'll update the docs asap

**Comment by ailispaw** [comment]
If it's possible to have both formats for compatibility, that would be great.

**Comment by aacebedo** [comment]
I'll check that however gnu long option are usually given with two hyphens (http://unix.stackexchange.com/questions/21852/single-dashes-for-single-character-options-but-double-dashes-for-words)
So even if I can add that I will be a deprecated feature with a short lifespan

**Comment by ailispaw** [comment]
That's fine. I believe that we need some time to transit new features before deprecation.

**Comment by ailispaw** [comment]
Or the documentation may be fine.
It's up to you.
Thank you for maintaining this project anyway.

**Comment by aacebedo** [comment]
You're welcome :)

**Comment by aacebedo** [comment]
I've checked the api for the command line parser. It unfortunately not possible to add flag with - and multiple characters.
