### ISSUE TITLE
v1.16.0 needs `--nameserver` option to resolve other domains than containers.

### ISSUE THREAD

**Issue by ailispaw** [aacebedo/dnsdock#80]
`-nameserver` option in v1.15.0 has the default value `8.8.8.8:53`, but the options in v1.16.0 seems null.
So in a container I can not ping domains like google.com.

**Comment by aacebedo** [comment]
Ok I'll fix it

**Comment by febbraro** [comment]
Has this been fixed, and just needs to be closed?

**Comment by aacebedo** [comment]
Yep it is fixed
