### ISSUE TITLE
Run on docker for windows/mac

### ISSUE THREAD

**Issue by whitecolor** [aacebedo/dnsdock#81]
Is it possible to run on on new docker for windows/mac?

**Comment by aacebedo** [comment]
Hi

I don't know if it works on those platforms. I do not own neither a Mac or a Windows but feel free to try and to send me a report :) I'll update the docs accordingly.

**Comment by whitecolor** [comment]
I tried to run (on docker for windows) and got this error:

`docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.0.1:53:53/udp aacebedo/dnsdock:latest-amd64`

```
socker: Error response from daemon: driver failed programming external connectivity on endpoint dnsdock (baa5145f4d1cb9212469b3d601b406a8287318e3b51d69189c1fa670d2956262): Error starting userland proxy: listen udp 172.17.0.1:53: bind: cannot assign requested address.
```

any suggestions?

**Comment by aacebedo** [comment]
Maybe it is a permission error on the windows host. Can you try to dig about that? 

Can you try to start a dummy container (ie alpine) such with the same port binding and start dns dock from it? 


Envoyé avec Boxer

Le 11 nov. 2016 2:19 PM, Alex <notifications@github.com> a écrit :

I tried to run (on docker for windows) and got this error:

docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.0.1:53:53/udp aacebedo/dnsdock:latest-amd64

socker: Error response from daemon: driver failed programming external connectivity on endpoint dnsdock (baa5145f4d1cb9212469b3d601b406a8287318e3b51d69189c1fa670d2956262): Error starting userland proxy: listen udp 172.17.0.1:53: bind: cannot assign requested address. 

any suggestions?

**Comment by whitecolor** [comment]
Well I've tried to start without IP:
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 53:53/udp aacebedo/dnsdock:latest-amd64

And in logs, it seem to find running container address:
```
2016/11/11 13:59:36 Handling DNS requests for docker.
2016/11/11 13:59:36 Started container '488b79bdf0a95e0cb0c6a5fb71c36045ed0ac842bd649113b018542e8d71351f'
2016/11/11 13:59:36 Added service: 488b79bdf0a95e0cb0c6a5fb71c36045ed0ac842bd649113b018542e8d71351f {dnsdock dnsdock 172.17.0.2 -1 []}
2016/11/11 13:59:36 Added service: ef82ea384aed3b14f92ea5379eaa2d527301d3a7d5c70178fb324ed1b182e02f {gceexp_web_1 gceexp_web 172.18.0.4 -1 []}
2016/11/11 13:59:36 Added service: 6974541b1e49cc7165d6b14b21aaad31208c24faf2ba7c546920616d8f353967 {gceexp_front-dev_1 gceexp_front-dev 172.18.0.3 -1 []}
2016/11/11 13:59:36 Added service: 9da6c9c0d0c3ec7761b95ea799e17e6bc0d3d3f70a3efb13f72797f0d8b8655c {gceexp_db_1 mongo 172.18.0.2 -1 []}
2016/11/11 13:59:36 Added service: 488b79bdf0a95e0cb0c6a5fb71c36045ed0ac842bd649113b018542e8d71351f {dnsdock dnsdock 172.17.0.2 -1 []}
```

But I can not access 53 port `telnet localhost 53`, and lookup `nslookup dnsdock localhost` (it doesn't work from within dnsdock container as well, should it?)

**Comment by whitecolor** [comment]
@aacebedo ah it seem started to work ok) thanks
