### ISSUE TITLE
Strange (container's) IP addresses resolved by dnsdock

### ISSUE THREAD

**Issue by whitecolor** [aacebedo/dnsdock#84]
Some strange behaviors that I observed but not figured out:

After some time Dnsdock may start to resolve some strange addresses:
`> nslookup client.manager.bbooks.dk` (`client.manager.bbooks.dk` is a DNS name of the container taken from by custom container's `label`)
```
Non-authoritative answer:
Name: client.manager.bbooks.dk
Addresses: 6.99.108.105
          172.18.0.2
```

Correct address is ` 172.18.0.2` don't know what is `6.99.108.105`, when `dnsdock` responses this way 
`> ping client.manager.bbooks.dk`:
```
The ping request could not find the host client.manager.bbooks.dk. Check the name and
Try again
```
though `> ping 172.18.0.2`  is reachable.
 
So have to restart `dnsdock` container to get rid of `6.99.108.105`.

Any suggestions?

**Comment by aacebedo** [comment]
Hi !
What version of dnsdock are you using ?
Can you run the following command on a linux host and copy the output:
dig @<DNS_DOCK_IP_ADDRESS> client.manager.bbooks.dk

dnsdock supports alias. However it's up to you to configure it.

**Comment by whitecolor** [comment]
I'm using `:v1.15.0-amd64`

This is from another linux container
```
root@b6f71feeca8f:/# dig @172.18.0.2 bbooks-rocher.k8s.dk
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.9.5-9+deb8u8-Debian <<>> @172.18.0.2 bbooks-rocher.k8s.dk
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43310
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: Message has 228 extra bytes at end

;; QUESTION SECTION:
;bbooks-rocher.k8s.dk.          IN      A

;; Query time: 1 msec
;; SERVER: 172.18.0.2#53(172.18.0.2)
;; WHEN: Sun Nov 27 06:48:44 UTC 2016
;; MSG SIZE  rcvd: 298
```

As you see there was 8 IP address for dns name of the container.

**Comment by aacebedo** [comment]
Hi

In your copy I see the answer counter but not the answers themselves.
Here is what I got when I issue a dig command on ubuntu 16.10. Notice the "ANSWER SECTION"
(I am using dnsdock 1.16.1)
```
$ dig @localhost -p 54 foo.example.com         

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @localhost -p 54 foo.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13176
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.example.com.		IN	A

;; ANSWER SECTION:
foo.example.com.	0	IN	A	172.17.0.3

;; Query time: 0 msec
;; SERVER: 127.0.0.1#54(127.0.0.1)
;; WHEN: Sun Nov 27 11:19:30 CET 2016
;; MSG SIZE  rcvd: 64
```

Now I think your issue may come from the way you've configured dnsdock and the way you've created your container instances.
Dnsdock builds its dns record by using metadata from the container instance. More specifically It uses the name of the instance, its image and the domain given to dnsdock.

If you start dnsdock this way:
`./dnsdocker --domain example.com`

DNS records will contain:
`<container instance name>.<container image name>.example.com`

It means that if you have multiple instance of the same container image you'll have multiple dns records with the same root `.<container image name>.example.com`

If you've instantiated multiple containers instance of your image "bbooks-rocher", you will receive multiple responses when resolving bbooks-rocher.k8s.dk (one per container using this image)

The solution might be to start your containers with the label com.dnsdock.image different for each container instance.

Can you check this ?

Regards

**Comment by whitecolor** [comment]
1) This name `bbooks-rocher.k8s.dk` stems from label `com.dnsdock.alias: bbooks-rocher.k8s.dk` on this container. 

2) I do not instantiate multiple instances at a time, but this image can often go up and down (by `docker-compose`) - so maybe there some problem. 

3) And another strange thingIP address given by DNS for this address contain correct address and other from absolutely unrelated scopes like `6.99.108.105`

**Comment by aacebedo** [comment]
I've reproduced your issue by starting and stopping the container! 
I am going to investigate this. 

Regards

**Comment by aacebedo** [comment]
See #65 for new flags
