### ISSUE TITLE
--nameserver option no longer parses multiple nameserver

### ISSUE THREAD

**Issue by febbraro** [aacebedo/dnsdock#86]
I noticed that in 1.16.0 it does not appear to be able to parse multiple comma separated nameservers. It looks like param parsing changed a lot. Is there a test for this? or any reason to think there is a regression?  I was seeing the following error:

DNS fowarding for 'dial udp: too many colons in address "10.10.7.2:53,8.8.8.8:53"' failed: no more nameservers to try

**Comment by aacebedo** [comment]
You can pass mutiple nameserver by passing multiple --nameserver arguments.
It prevents dnsdock to parse the argument --nameserver and let the arguments parsing library to deal with that.

**Comment by febbraro** [comment]
That was it. Using multiple --nameserver arguments works. Thanks. We should likely update the docs to represent that.
