### ISSUE TITLE
Some additional documentation / support around development

### ISSUE THREAD

**Issue by febbraro** [aacebedo/dnsdock#94]
Hello,

I'm having a difficult time understanding how one is expected to develop PRs for dnsdock. I have forked the repo into my organization, phase2/dnsdock. 

I checkout that repo, from the root I go a godep restore, then I cd into the src dir and when I do a build (go build) I get the following errors.

```
main.go:19:2: cannot find package "github.com/aacebedo/dnsdock/src/core" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/github.com/aacebedo/dnsdock/src/core (from $GOROOT)
	/Users/frank/Projects/go/src/github.com/aacebedo/dnsdock/src/core (from $GOPATH)
main.go:20:2: cannot find package "github.com/aacebedo/dnsdock/src/servers" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/github.com/aacebedo/dnsdock/src/servers (from $GOROOT)
	/Users/frank/Projects/go/src/github.com/aacebedo/dnsdock/src/servers (from $GOPATH)
main.go:21:2: cannot find package "github.com/aacebedo/dnsdock/src/utils" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/github.com/aacebedo/dnsdock/src/utils (from $GOROOT)
	/Users/frank/Projects/go/src/github.com/aacebedo/dnsdock/src/utils (from $GOPATH)
```

If is it referencing your (aacebedo) paths directly from within the dnsdock code itself, how are any changes I am making in my fork/repo able to get built into the binary?  I am simply trying to build the dnsdock binary, I can make a simple Dockerfile to create a local image for testing, but it appears that only commit changes into your repo directly can be built.  Am I mistaken?

Any pointers would be greatly appreciated.

Thanks!

**Comment by febbraro** [comment]
The changes I am making are in the core and servers packages

**Comment by aacebedo** [comment]
Hi !
Thanks for taking time to improve dnsdock
Having the name of the original repo is okay on a go program.
The best way to compile dnsdock is to use rocker and docker. You have a rockerfile in the repo.
So you can clone your fork on your host and mount it in the build container.
Within it everything shall be configured correctly
